/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1ec49c43-3893-41e4-bf12-010843d0e228

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We proved that the sum of the first n natural numbers is n(n+1)/2 using induction on n. The formal statement is `sum_first_n`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The sum of natural numbers from 1 to n is n(n+1)/2.
-/
open Finset

theorem sum_first_n (n : ℕ) : ∑ k ∈ Ico 1 (n + 1), k = n * (n + 1) / 2 := by
  exact Eq.symm ( Nat.div_eq_of_eq_mul_left zero_lt_two <| Nat.recOn n ( by norm_num ) fun n ih => by norm_num [ Finset.sum_Ico_succ_top ] at * ; linarith )